import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import FieldLabel from '@/pages/Accounts/BatchProcedures/lib/BatchFieldLabel';
import {apiJson} from '@/lib/api';
const base=`${import.meta.env.VITE_APP_FIN_URL}/api/backoffice/loan-ageing`;
const normalize=v=>Array.isArray(v)?v.map(normalize):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k[0].toLowerCase()+k.slice(1),normalize(x)])):v;
async function request(path,options){const r=await apiJson(base+path,{cache:'no-store',...options});return normalize(r.data??r.Data);}
const money=n=>Number(n??0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function GeneratedSchedules({cases,onClose,onSaved}){
 const [rows,setRows]=useState([]),[selected,setSelected]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;Promise.allSettled(cases.map(c=>request(`/cases/${c.id}/schedule-proposal`))).then(results=>{if(!active)return;const proposals=results.map((r,i)=>r.status==='fulfilled'?{loan:cases[i],...r.value}:{loan:cases[i],error:r.reason.message});setRows(proposals);setSelected(proposals.filter(r=>r.canConfirm).map(r=>r.loan.id));setLoading(false);});return()=>{active=false;};},[cases]);
 async function save(){setBusy(true);setError('');try{const saved=await request('/generated-schedules/confirm',{method:'POST',body:JSON.stringify(rows.filter(r=>selected.includes(r.loan.id)).map(r=>({loanCaseId:r.loan.id,revision:r.plan.revision,proposalHash:r.proposalHash})))});onSaved(saved);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="fixed inset-0 z-50 flex justify-end bg-black/40"><section role="dialog" aria-modal="true" aria-label="Generate existing loan schedules" className="m-2 w-full max-w-5xl bg-white rounded-2xl flex flex-col shadow-2xl">
  <header className="m-2 p-4 rounded-2xl bg-indigo-600 text-white flex justify-between items-center shrink-0"><h2 className="font-bold">Generate existing loan schedules</h2><Button variant="outline" disabled={busy} onClick={onClose}>Close</Button></header>
  <div className="flex-1 overflow-y-auto p-5 space-y-4">
   <FieldLabel label="Preview from saved loan terms" help="Uses original posted principal, the disbursement date and terms stored against each loan case. End-of-period payments start after one repayment interval; beginning-of-period payments start at disbursement, plus the saved grace period. Upfront interest is taken from the original charge and entered once. This confirms repayment schedules for ageing; report adjustments are made in Excel."/>
   <p className="text-sm text-gray-700">{cases.length} unconfirmed cases from the current page. Review the dates and amounts, then save the selected schedules as new revisions.</p>
   {error&&<p role="alert" className="bg-red-50 text-red-700 p-3 rounded-lg">{error}</p>}
   {loading?<p role="status" className="animate-pulse text-gray-500">Generating schedules…</p>:<div className="bg-gray-200 p-3 rounded-sm"><div className="grid grid-cols-12 gap-3 bg-gray-700 text-gray-100 font-semibold p-3 rounded-lg mb-3"><span className="col-span-2">Confirm / Case</span><span className="col-span-3">Principal</span><span className="col-span-3">First / last due</span><span className="col-span-4">Schedule</span></div><div className="space-y-2">{rows.map(r=><article key={r.loan.id} className="bg-white border rounded-lg shadow-lg p-3 text-sm text-gray-700">
    <div className="grid grid-cols-12 gap-3 items-center"><label className="col-span-2 flex gap-2 items-center"><input type="checkbox" className="w-4 h-4 accent-indigo-600" aria-label={`Confirm case ${r.loan.caseNumber}`} disabled={busy||!r.canConfirm} checked={selected.includes(r.loan.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,r.loan.id]:v.filter(x=>x!==r.loan.id))}/><strong>{r.loan.caseNumber}</strong></label><span className="col-span-3">{r.plan?money(r.plan.principal):'Unavailable'}</span><span className="col-span-3">{r.plan?<>{r.plan.instalments[0]?.dueDate.slice(0,10)}<br/>{r.plan.instalments.at(-1)?.dueDate.slice(0,10)}</>:'—'}</span><span className="col-span-4">{r.plan?`${r.plan.instalments.length} instalments · Interest KSh ${money(r.plan.instalments.reduce((n,x)=>n+Number(x.interest??0),0))}`:r.error}</span></div>
    {r.warnings?.map(w=><p key={w} className="text-amber-700 mt-2">{w}</p>)}
    {r.plan&&<details className="mt-3"><summary className="cursor-pointer text-indigo-700">Terms and instalments</summary><p className="my-2">{r.terms}</p><div className="max-h-64 overflow-auto"><div className="grid grid-cols-5 gap-2 bg-gray-100 p-2 font-semibold"><span>Instalment</span><span>Principal due</span><span>Principal</span><span>Interest</span><span>Interest due</span></div>{r.plan.instalments.map(x=><div key={x.number} className="grid grid-cols-5 gap-2 border-t p-2"><span>{x.number}</span><span>{x.dueDate.slice(0,10)}</span><span>{money(x.principal)}</span><span>{money(x.interest)}</span><span>{x.interestDueDate?.slice(0,10)||'—'}</span></div>)}</div></details>}
   </article>)}</div></div>}
  </div><footer className="shrink-0 border-t p-4 flex justify-between gap-3 items-center"><span className="text-sm text-gray-600">{selected.length} schedules selected</span><Button className="bg-indigo-600 hover:bg-indigo-700" disabled={loading||busy||!selected.length} onClick={save}>{busy?'Saving…':'Confirm and save selected schedules'}</Button></footer>
 </section></div>;
}
