import { useEffect, useState } from 'react';
import { FaCalendarAlt } from 'react-icons/fa';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import FieldLabel from '@/pages/Accounts/BatchProcedures/lib/BatchFieldLabel';
import { apiJson } from '@/lib/api';
import Swal from 'sweetalert2';
import { allocationPolicy, equalPrincipalSchedule, validatePlan } from './model';
import GeneratedSchedules from './GeneratedSchedules';
const base = `${import.meta.env.VITE_APP_FIN_URL}/api/backoffice/loan-ageing`;
const normalize = v => Array.isArray(v) ? v.map(normalize) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k,x])=>[k[0].toLowerCase()+k.slice(1),normalize(x)])) : v;
async function request(path, options) { const r = await apiJson(base + path, {cache:'no-store', ...options}); return normalize(r.data ?? r.Data); }
const money = x => Number(x || 0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});
const today = () => { const d = new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const primary = 'bg-indigo-600 hover:bg-indigo-700';
function Pager({page,total,onChange,disabled}) {const pages=Math.max(1,Math.ceil(total/20));return <div className="flex justify-center gap-3 items-center mt-4"><Button disabled={disabled || page===0} onClick={()=>onChange(page-1)}>Prev</Button><span>Page {page+1} of {pages}</span><Button disabled={disabled || page+1>=pages} onClick={()=>onChange(page+1)}>Next</Button></div>;}
export default function LoanAgeing({onClose}) {
 const [view,setView]=useState('schedules'),[cases,setCases]=useState({items:[],total:0}),[search,setSearch]=useState(''),[text,setText]=useState(''),[page,setPage]=useState(0),[reload,setReload]=useState(0);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [asAt,setAsAt]=useState(today),[reportDate,setReportDate]=useState(''),[report,setReport]=useState(null),[reportPage,setReportPage]=useState(0),[detail,setDetail]=useState(null),[detailPage,setDetailPage]=useState(0),[interestPage,setInterestPage]=useState(0);
 const [plan,setPlan]=useState(null),[selectedCase,setSelectedCase]=useState(null),[dirty,setDirty]=useState(false),[linePage,setLinePage]=useState(0),[history,setHistory]=useState(null);
 const [firstDue,setFirstDue]=useState(''),[count,setCount]=useState(1),[months,setMonths]=useState(1);
 const [generationCases,setGenerationCases]=useState(null),[proposal,setProposal]=useState(null);
 useEffect(()=>{const timer=setTimeout(()=>{setText(search.trim());setPage(0);},350);return()=>clearTimeout(timer);},[search]);
 useEffect(()=>{let active=true;setLoading(true);setError('');request(`/cases?text=${encodeURIComponent(text)}&pageIndex=${page}&pageSize=20`).then(r=>{if(active)setCases(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[text,page,reload]);
 useEffect(()=>{if(!reportDate)return;let active=true;setLoading(true);setError('');request(`/report?asAt=${reportDate}&pageIndex=${reportPage}&pageSize=20`).then(r=>{if(active)setReport(r);}).catch(e=>{if(active){setReport(null);setError(e.message);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[reportDate,reportPage,reload]);
 async function run(action){setBusy(true);setError('');setNotice('');try{await action();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function openPlan(c){await run(async()=>{const p=await request(`/cases/${c.id}/plan`);setPlan(p);setProposal(null);setSelectedCase(c);setDirty(false);setHistory(null);setLinePage(0);setFirstDue('');setCount(Math.max(1,Math.round(c.termMonths*c.frequency/12)));setMonths(c.frequency>0&&12%c.frequency===0?12/c.frequency:1);});}
 function changePlan(change){setPlan(p=>({...p,...change,isConfirmed:false}));setDirty(true);}
 async function closePlan(){if(dirty&&!(await Swal.fire({title:'Discard unsaved schedule changes?',icon:'question',showCancelButton:true,confirmButtonText:'Discard'})).isConfirmed)return;setPlan(null);setDirty(false);setHistory(null);}
 const waiting=busy||loading;
 return <main className="bg-white m-8 px-8 py-8 shadow-2xl rounded-lg relative">
  <header className="bg-indigo-800 px-6 py-3 rounded-2xl flex justify-between items-center gap-3"><h1 className="text-xl font-bold text-white flex gap-2 items-center"><FaCalendarAlt/>Loan Ageing</h1>{onClose&&<Button variant="outline" disabled={waiting} onClick={onClose}>Back</Button>}</header>
  <div className="my-4 text-sm text-gray-700"><FieldLabel label="Principal and interest ageing · All branches · KSh" help="Compare confirmed principal and interest terms with posted movements. Interest uses its own contractual due dates and settlements. Combined days overdue requires both components to be resolved. Confirmed restructuring schedules use their saved opening allocations. Form 4 provides separately reviewed classifications and provisions."/></div>
  <div className="flex flex-wrap gap-2 mb-4"><Button disabled={waiting} variant={view==='schedules'?'default':'outline'} onClick={()=>setView('schedules')}>Repayment schedules</Button><Button disabled={waiting} variant={view==='ageing'?'default':'outline'} onClick={()=>setView('ageing')}>Ageing report</Button><Button disabled={waiting} variant="outline" onClick={()=>setReload(n=>n+1)}>Refresh</Button></div>
  {error&&<p role="alert" className="p-3 mb-3 rounded-lg bg-red-50 border border-red-200 text-red-700">{error}</p>}{notice&&<p role="status" className="text-green-700 mb-3">{notice}</p>}
  {view==='schedules'?<>
   <div className="mb-4"><Button className={primary} disabled={waiting||!cases.items.some(c=>!c.isConfirmed)} onClick={()=>setGenerationCases(cases.items.filter(c=>!c.isConfirmed))}>Generate unconfirmed schedules on this page</Button></div>
   <div className="max-w-md mb-4"><FieldLabel label="Find a loan case" help="Search by case number or loan product. Results are filtered and paged on the server, including newly disbursed loans."/><Input aria-label="Find a loan case" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Case number or product"/></div>
   <div className="bg-gray-200 p-4 rounded-sm"><div className="grid grid-cols-12 gap-3 bg-gray-700 text-gray-100 font-semibold p-3 rounded-lg mb-4"><span className="col-span-2">Case</span><span className="col-span-4">Product</span><span className="col-span-3 text-right">Disbursed</span><span className="col-span-3">Schedule</span></div><div className="space-y-2">{loading?[1,2,3].map(n=><div key={n} className="animate-pulse h-12 bg-gray-50 rounded-lg"/>):cases.items.map(c=><button key={c.id} disabled={busy} onClick={()=>openPlan(c)} className="w-full text-left grid grid-cols-12 gap-3 items-center p-3 bg-white rounded-lg shadow-lg border hover:shadow-xl transition-all text-sm text-gray-700 focus-visible:outline-indigo-600"><strong className="col-span-2">{c.caseNumber}</strong><span className="col-span-4">{c.product}</span><span className="col-span-3 text-right tabular-nums">{money(c.disbursedAmount)}</span><span className={`col-span-3 text-xs font-semibold ${c.isConfirmed?'text-green-700':'text-amber-700'}`}>{c.planRevision?`Revision ${c.planRevision} · ${c.isConfirmed?'Confirmed':'Review required'}`:'Schedule required'}</span></button>)}</div>{!loading&&!cases.items.length&&<Empty label="No matching loan cases."/>}</div>
   <Pager page={page} total={cases.total} disabled={waiting} onChange={setPage}/>
  </>:<>
   <form className="flex flex-wrap gap-3 items-end mb-4" onSubmit={e=>{e.preventDefault();setReportPage(0);setReportDate(asAt);setReload(n=>n+1);}}><div><FieldLabel label="As at" help="Includes postings for the entire selected day, using journal value date and creation date as fallback. An instalment becomes overdue the day after its due date. Backdated postings may change historical results."/><Input type="date" required min="1753-01-01" max="9998-12-31" aria-label="Ageing as at" value={asAt} onChange={e=>setAsAt(e.target.value)}/></div><Button className={primary} disabled={waiting} type="submit">Calculate ageing</Button></form>
   {report&&<><div className="border rounded-lg p-4 mb-4 text-sm space-y-3"><strong>Position at {report.asAt.slice(0,10)}</strong><div className="flex flex-wrap gap-5"><span>Principal: {money(report.accountPrincipal)}</span><FieldLabel label={`Known overdue: ${money(report.knownOverduePrincipal)}`} help="Overdue principal from accounts with complete confirmed schedules only. Accounts requiring review are excluded, so this is not a complete portfolio arrears figure until every issue is resolved."/><span>Principal review: {report.accountsRequiringReview}</span><span>Interest review: {report.interestAccountsRequiringReview}</span><FieldLabel label={`Known overdue interest: ${money(report.knownOverdueInterest)}`} help="Excludes accounts with unresolved interest terms or posting issues. This is not a complete portfolio total while interest review remains outstanding."/><FieldLabel label={`Interest G/L difference: ${money(report.interestDifference)}`} help="Customer-account interest receivable minus the interest-receivable G/L total. This control is separate from contractual interest that has not yet been charged."/><FieldLabel label={`G/L difference: ${money(report.difference)}`} help="Customer loan-account principal minus the loan-principal G/L total. A nonzero difference requires investigation of missing customer links, account types or mappings."/></div>{report.issues.map(x=><p key={x} className="text-red-700">{x}</p>)}<FieldLabel label="Allocation and report limitations" help={report.warnings.join(' ')}/></div>
   <div className="bg-gray-200 p-4 rounded-sm"><div className="grid grid-cols-12 gap-3 bg-gray-700 text-gray-100 font-semibold p-3 rounded-lg mb-4"><span className="col-span-2">Loan cases</span><span className="col-span-2 text-right">Principal</span><span className="col-span-2 text-right">Principal overdue</span><span className="col-span-2 text-right">Interest overdue</span><span className="col-span-2 text-right">Combined days</span><span className="col-span-2">Combined status</span></div><div className="space-y-2">{report.accounts.map(a=><button key={a.customerAccountId} disabled={waiting} onClick={()=>run(async()=>{const r=await request(`/report?asAt=${reportDate}&accountId=${a.customerAccountId}`);setDetail(r.accounts[0]);setDetailPage(0);setInterestPage(0);})} className="w-full text-left grid grid-cols-12 gap-3 items-center p-3 bg-white rounded-lg shadow-lg border hover:shadow-xl transition-all text-sm text-gray-700 focus-visible:outline-indigo-600"><span className="col-span-2">{a.caseNumbers.join(', ')||'Unlinked case'}</span><span className="col-span-2 text-right tabular-nums">{money(a.outstandingPrincipal)}</span><span className="col-span-2 text-right tabular-nums">{a.overduePrincipal==null?'Unknown':money(a.overduePrincipal)}</span><span className="col-span-2 text-right tabular-nums">{a.interest?.overdueInterest==null?'Unknown':money(a.interest.overdueInterest)}</span><span className="col-span-2 text-right">{a.combinedDaysPastDue??'Unknown'}</span><span className={`col-span-2 ${a.combinedDaysPastDue==null?'text-amber-700':'text-gray-700'}`}>{a.combinedBucket}</span></button>)}</div>{!report.accounts.length&&<Empty label="No loan accounts in this reporting scope."/>}</div><Pager page={reportPage} total={report.totalAccounts} disabled={waiting} onChange={setReportPage}/></>}
  </>}
  {generationCases&&<GeneratedSchedules cases={generationCases} onClose={()=>setGenerationCases(null)} onSaved={saved=>{setGenerationCases(null);setReload(n=>n+1);setNotice(`${saved.length} confirmed schedule revisions saved. Recalculate ageing or preview Form 4.`);}}/>}
  {plan&&<div className="fixed inset-0 z-50 flex justify-end bg-black/40"><section role="dialog" aria-modal="true" aria-label="Loan repayment schedule" className="bg-white rounded-2xl m-2 w-full max-w-4xl flex flex-col shadow-2xl"><header className="m-2 bg-indigo-600 text-white rounded-2xl p-4 flex justify-between items-center shrink-0"><h2 className="font-bold">Case {plan.caseNumber} · Repayment schedule</h2><Button variant="outline" disabled={busy} onClick={closePlan}>Close</Button></header><div className="flex-1 overflow-y-auto px-5 py-3 space-y-4">
   {error&&<p role="alert" className="p-3 bg-red-50 text-red-700 rounded-lg">{error}</p>}
   <div className="flex flex-wrap justify-between gap-3 text-sm"><span>{selectedCase?.product} · Principal KSh {money(plan.principal)}</span><span>{plan.revision?`Revision ${plan.revision} · ${plan.isConfirmed?'Confirmed':'Review required'}`:'No saved schedule'}</span></div>
   {!plan.isRestructuring&&<Button className={primary} disabled={busy} onClick={async()=>{if((dirty||plan.instalments.length>0)&&!(await Swal.fire({title:'Regenerate the displayed schedule?',text:'The preview uses saved loan-case terms and the original disbursement. Saved revisions remain in history.',icon:'question',showCancelButton:true,confirmButtonText:'Generate preview'})).isConfirmed)return;run(async()=>{const r=await request(`/cases/${plan.loanCaseId}/schedule-proposal`);setPlan(r.plan);setProposal(r);setDirty(true);setLinePage(0);setHistory(null);});}}>Generate from saved loan terms</Button>}
   {proposal&&<div className="border rounded-lg p-3 text-sm space-y-2"><p>{proposal.terms}</p>{proposal.warnings.map(w=><p key={w} className="text-amber-700">{w}</p>)}</div>}
   {plan.isRestructuring&&<div className="border border-amber-200 bg-amber-50 rounded-lg p-3 space-y-3 text-sm"><FieldLabel label="Replacement schedule and opening allocation" help="This schedule replaces the linked prior schedules from the restructuring posting boundary. Earlier reports retain the original terms. Prior ledger changes invalidate the opening snapshot. Saving these terms does not change loan balances or upgrade risk classification."/><p>Effective: {plan.effectiveAt?.replace('T',' ')} · Opening principal: {money(plan.principal)} · Opening interest: {money(plan.openingInterest)}</p><div><FieldLabel label="Retained pre-restructure category" help="Confirm the category immediately before restructuring. It cannot be better than the old schedule's calculated category or a previously retained category. If prior schedules are missing, confirm them first. This minimum is retained in Form 4 until a separate supported reclassification workflow is implemented."/><select aria-label="Retained pre-restructure category" className="w-full border rounded-md p-2" value={plan.priorRiskCategory??''} onChange={e=>changePlan({priorRiskCategory:e.target.value===''?null:Number(e.target.value)})}><option value="">Prior schedules require confirmation</option>{['Performing','Watch','Substandard','Doubtful','Loss'].map((x,i)=><option key={x} value={i}>{x}</option>)}</select></div><details><summary>Previous schedule revision references</summary><p className="break-all">{plan.priorPlanIds||'Confirm original schedules first.'}</p></details></div>}
   <FieldLabel label="Contractual repayment schedule" help="Enter the contractual principal instalments for this loan case, including instalments already paid. Do not reduce the schedule by repayments; ageing reads those from the ledger. Saving creates a new immutable revision. This editor corrects original schedules; it must not be used to replace terms after a restructuring. Enter interest separately, using its contractual due date. For upfront interest, enter the total once with the disbursement date; enter zero in other rows. Generated interest is a proposal and may need correction for minimum charges or upfront recovery."/>
   <div className="grid sm:grid-cols-4 gap-3 p-3 border rounded-lg items-end"><div><FieldLabel label="First due date" help="Use the signed agreement or approved repayment terms, not the date on which you are generating this schedule."/><Input type="date" aria-label="First due date" min={plan.disbursementDate.slice(0,10)} value={firstDue} onChange={e=>setFirstDue(e.target.value)}/></div><div><FieldLabel label="Instalments" help="For the optional equal-principal generator only. Use the actual number of contractual instalments."/><Input aria-label="Number of instalments" type="number" min="1" max="1200" value={count} onChange={e=>setCount(e.target.value)}/></div><div><FieldLabel label="Months between" help="This helper generates monthly intervals only. Other frequencies and amortized principal amounts can be entered by editing individual rows."/><Input aria-label="Months between instalments" type="number" min="1" max="12" value={months} onChange={e=>setMonths(e.target.value)}/></div><Button variant="outline" disabled={busy} onClick={async()=>{if(plan.instalments.length&&!(await Swal.fire({title:'Replace the displayed instalments?',text:'This changes the unsaved schedule only.',icon:'question',showCancelButton:true,confirmButtonText:'Replace'})).isConfirmed)return;try{changePlan({instalments:equalPrincipalSchedule(plan.principal,firstDue,count,months)});setLinePage(0);setError('');}catch(e){setError(e.message);}}}>Generate equal principal</Button></div>
   <div className="bg-gray-200 p-3 rounded-sm"><div className="grid grid-cols-12 gap-3 p-3 rounded-lg bg-gray-700 text-gray-100 font-semibold mb-3"><span>No.</span><span className="col-span-3">Principal due</span><span className="col-span-2">Principal</span><span className="col-span-2"><FieldLabel label="Interest" help="Agreed interest, excluding principal. Enter zero explicitly when none is due; blank means unconfirmed. Never use a zero receivable balance to assume interest-free terms."/></span><span className="col-span-3"><FieldLabel label="Interest due" help="Contractual payment date, which can differ from principal. Upfront interest is due on disbursement. Only positive interest needs a date."/></span></div><div className="space-y-2">{plan.instalments.slice(linePage*20,linePage*20+20).map((r,i)=>{const index=linePage*20+i;return <div key={index} className="grid grid-cols-12 gap-3 items-center p-3 bg-white rounded-lg border shadow-lg"><span>{index+1}</span><Input className="col-span-3" aria-label={`Instalment ${index+1} due date`} type="date" value={r.dueDate.slice(0,10)} disabled={busy} onChange={e=>changePlan({instalments:plan.instalments.map((x,n)=>n===index?{...x,dueDate:e.target.value}:x)})}/><Input className="col-span-2" aria-label={`Instalment ${index+1} principal`} type="number" step="0.01" min="0.01" value={r.principal} disabled={busy} onChange={e=>changePlan({instalments:plan.instalments.map((x,n)=>n===index?{...x,principal:e.target.value}:x)})}/><Input className="col-span-2" aria-label={`Instalment ${index+1} interest`} type="number" step="0.01" min="0" value={r.interest??''} disabled={busy} onChange={e=>changePlan({interestTermsConfirmed:false,instalments:plan.instalments.map((x,n)=>n===index?{...x,interest:e.target.value}:x)})}/><Input className="col-span-3" aria-label={`Instalment ${index+1} interest due date`} type="date" value={r.interestDueDate?.slice(0,10)||''} disabled={busy} onChange={e=>changePlan({interestTermsConfirmed:false,instalments:plan.instalments.map((x,n)=>n===index?{...x,interestDueDate:e.target.value}:x)})}/><button className="text-red-700" disabled={busy} aria-label={`Remove instalment ${index+1}`} onClick={()=>{changePlan({instalments:plan.instalments.filter((_,n)=>n!==index).map((x,n)=>({...x,number:n+1}))});setLinePage(0);}}>×</button></div>;})}</div></div>
   <div className="flex justify-between items-center gap-3"><Button variant="outline" disabled={busy||plan.instalments.length>=1200} onClick={()=>{changePlan({instalments:[...plan.instalments,{number:plan.instalments.length+1,dueDate:'',principal:''}]});setLinePage(Math.floor(plan.instalments.length/20));}}>Add instalment</Button><span className="text-sm">Principal total: KSh {money(plan.instalments.reduce((n,r)=>n+Number(r.principal||0),0))}</span></div><Pager page={linePage} total={plan.instalments.length} disabled={busy} onChange={setLinePage}/>
   <label className="flex items-start gap-2 text-sm"><input type="checkbox" className="w-4 h-4 accent-indigo-600" disabled={busy} checked={!!plan.interestTermsConfirmed} onChange={e=>changePlan({interestTermsConfirmed:e.target.checked})}/><FieldLabel label="I have confirmed the interest amounts and due dates" help="Confirm against approved terms, including upfront recovery or zero interest. Leave unchecked to save principal terms while interest remains Needs review. Saving does not charge interest or post repayments."/></label>
   <div><FieldLabel label="Supporting evidence" help="Identify the loan agreement, approved first-payment date and repayment terms you used. Record why a correction is necessary. Do not use this field to assume missing terms."/><textarea aria-label="Supporting evidence" maxLength={2000} className="w-full border rounded-md p-2 text-sm" rows={3} disabled={busy} value={plan.evidence||''} onChange={e=>changePlan({evidence:e.target.value})}/></div>
   <label className="flex gap-2 text-sm items-start"><input type="checkbox" className="w-4 h-4 accent-indigo-600" checked={plan.isConfirmed} disabled={busy} onChange={e=>{setPlan(p=>({...p,isConfirmed:e.target.checked}));setDirty(true);}}/>I have checked the principal instalments and contractual due dates against the supporting records.</label>
   <Button variant="outline" disabled={busy||!plan.revision} onClick={()=>run(async()=>setHistory(await request(`/cases/${plan.loanCaseId}/history`)))}>View revision history</Button>
   {history&&<div className="space-y-3 border rounded-lg p-3 text-sm">{history.map(v=><details key={v.id}><summary>Revision {v.revision} · {v.isConfirmed?'Confirmed':'Captured draft'} · {v.createdDate?.slice(0,10)} · {v.createdBy}</summary><p className="my-2">{v.evidence}</p><div className="max-h-56 overflow-y-auto">{v.instalments.map(r=><div key={r.number} className="grid grid-cols-3 border-t p-1"><span>{r.number}</span><span>{r.dueDate.slice(0,10)}</span><span className="text-right">{money(r.principal)} principal · {r.interest==null?'Unconfirmed':money(r.interest)} interest {r.interestDueDate?.slice(0,10)}</span></div>)}</div><p>Interest terms: {v.interestTermsConfirmed?'Confirmed':'Not confirmed'}</p></details>)}</div>}
  </div><footer className="border-t p-4 shrink-0 flex justify-end"><Button className={primary} disabled={busy||(!dirty&&plan.isConfirmed)} onClick={()=>{const payload={...plan,allocationPolicy,instalments:plan.instalments.map((r,i)=>({...r,number:i+1,principal:Number(r.principal),interest:r.interest==null||r.interest===''?null:Number(r.interest),interestDueDate:r.interestDueDate||null}))};const message=validatePlan(payload);if(message){setError(message);return;}run(async()=>{const saved=await request('/plans',{method:'POST',body:JSON.stringify(payload)});setPlan(saved);setDirty(false);setHistory(null);setReload(n=>n+1);setNotice(`Case ${saved.caseNumber}: confirmed schedule revision ${saved.revision} saved.`);});}}>Save confirmed revision</Button></footer></section></div>}
  {detail&&<div className="fixed inset-0 z-50 bg-black/40 flex justify-end"><section role="dialog" aria-modal="true" aria-label="Ageing account detail" className="bg-white rounded-2xl m-2 w-full max-w-4xl flex flex-col"><header className="m-2 rounded-2xl bg-indigo-600 text-white p-4 flex justify-between shrink-0"><h2 className="font-bold">Cases {detail.caseNumbers.join(', ')} · {reportDate}</h2><Button variant="outline" onClick={()=>setDetail(null)}>Close</Button></header><div className="flex-1 overflow-y-auto p-5"><p className="mb-3">Outstanding principal: KSh {money(detail.outstandingPrincipal)}</p>{detail.issues.map(x=><p key={x} className="text-amber-700 mb-2">{x}</p>)}<div className="bg-gray-200 p-3 rounded-sm"><div className="grid grid-cols-5 gap-2 bg-gray-700 text-white p-3 rounded-lg mb-2 text-sm"><span>Case / instalment</span><span>Due date</span><span>Principal</span><span>Allocated</span><span>Remaining</span></div><div className="space-y-2">{detail.instalments.slice(detailPage*20,detailPage*20+20).map(r=><div key={`${r.planId}:${r.number}`} className="grid grid-cols-5 gap-2 bg-white p-3 border shadow-lg rounded-lg text-sm"><span>{r.caseNumber} / {r.number}</span><span>{r.dueDate.slice(0,10)}</span><span>{money(r.principal)}</span><span>{money(r.allocatedPrincipal)}</span><span>{money(r.remainingPrincipal)}</span></div>)}</div></div><Pager page={detailPage} total={detail.instalments.length} disabled={false} onChange={setDetailPage}/>
   <section className="border-t mt-6 pt-4"><h3 className="font-semibold mb-3">Interest ageing</h3><div className="flex flex-wrap gap-4 text-sm mb-3"><span>Receivable: {money(detail.interest?.receivable)}</span><span>Interest days overdue: {detail.interest?.daysPastDue??'Unknown'}</span><FieldLabel label={`Due but uncharged: ${detail.interest?.unaccruedDueInterest==null?'Unknown':money(detail.interest.unaccruedDueInterest)}`} help="Contractual interest due to date less cumulative posted charges, floored at zero. An amount here requires accrual review and prevents a complete interest-ageing result."/></div>{detail.interest?.issues.map(x=><p key={x} className="text-amber-700 mb-2">{x}</p>)}<div className="bg-gray-200 p-3 rounded-sm"><div className="grid grid-cols-5 gap-2 bg-gray-700 text-white p-3 rounded-lg mb-2 text-sm"><span>Case / instalment</span><span>Interest due</span><span>Interest</span><span>Allocated</span><span>Remaining</span></div><div className="space-y-2">{detail.interest?.instalments.slice(interestPage*20,interestPage*20+20).map(r=><div key={`${r.planId}:${r.number}`} className="grid grid-cols-5 gap-2 bg-white p-3 border shadow-lg rounded-lg text-sm"><span>{r.caseNumber} / {r.number}</span><span>{r.dueDate.slice(0,10)}</span><span>{money(r.interest)}</span><span>{money(r.allocatedInterest)}</span><span>{money(r.remainingInterest)}</span></div>)}</div></div><Pager page={interestPage} total={detail.interest?.instalments.length||0} disabled={false} onChange={setInterestPage}/></section></div></section></div>}
 </main>;
}
function Empty({label}){return <div className="text-center py-6"><img src="/assets/scopefinding.png" className="w-32 mx-auto" alt=""/><p className="text-gray-400">{label}</p></div>;}
